
package com.mikovoz;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ShopService", targetNamespace = "http://mikovoz.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ShopService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addItem", targetNamespace = "http://mikovoz.com/", className = "com.mikovoz.AddItem")
    @ResponseWrapper(localName = "addItemResponse", targetNamespace = "http://mikovoz.com/", className = "com.mikovoz.AddItemResponse")
    @Action(input = "http://mikovoz.com/ShopService/addItemRequest", output = "http://mikovoz.com/ShopService/addItemResponse")
    public void addItem(
        @WebParam(name = "arg0", targetNamespace = "")
        Items arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.mikovoz.Items
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getItem", targetNamespace = "http://mikovoz.com/", className = "com.mikovoz.GetItem")
    @ResponseWrapper(localName = "getItemResponse", targetNamespace = "http://mikovoz.com/", className = "com.mikovoz.GetItemResponse")
    @Action(input = "http://mikovoz.com/ShopService/getItemRequest", output = "http://mikovoz.com/ShopService/getItemResponse")
    public Items getItem(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addSeller", targetNamespace = "http://mikovoz.com/", className = "com.mikovoz.AddSeller")
    @ResponseWrapper(localName = "addSellerResponse", targetNamespace = "http://mikovoz.com/", className = "com.mikovoz.AddSellerResponse")
    @Action(input = "http://mikovoz.com/ShopService/addSellerRequest", output = "http://mikovoz.com/ShopService/addSellerResponse")
    public void addSeller(
        @WebParam(name = "arg0", targetNamespace = "")
        Sellers arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.mikovoz.Sellers
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSeller", targetNamespace = "http://mikovoz.com/", className = "com.mikovoz.GetSeller")
    @ResponseWrapper(localName = "getSellerResponse", targetNamespace = "http://mikovoz.com/", className = "com.mikovoz.GetSellerResponse")
    @Action(input = "http://mikovoz.com/ShopService/getSellerRequest", output = "http://mikovoz.com/ShopService/getSellerResponse")
    public Sellers getSeller(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

}
