
package com.mikovoz;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ShopServiceService", targetNamespace = "http://mikovoz.com/", wsdlLocation = "http://localhost:7001/java-1.0-SNAPSHOT/ShopServiceService?WSDL")
public class ShopServiceService
    extends Service
{

    private final static URL SHOPSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SHOPSERVICESERVICE_EXCEPTION;
    private final static QName SHOPSERVICESERVICE_QNAME = new QName("http://mikovoz.com/", "ShopServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7001/java-1.0-SNAPSHOT/ShopServiceService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SHOPSERVICESERVICE_WSDL_LOCATION = url;
        SHOPSERVICESERVICE_EXCEPTION = e;
    }

    public ShopServiceService() {
        super(__getWsdlLocation(), SHOPSERVICESERVICE_QNAME);
    }

    public ShopServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SHOPSERVICESERVICE_QNAME, features);
    }

    public ShopServiceService(URL wsdlLocation) {
        super(wsdlLocation, SHOPSERVICESERVICE_QNAME);
    }

    public ShopServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SHOPSERVICESERVICE_QNAME, features);
    }

    public ShopServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ShopServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ShopService
     */
    @WebEndpoint(name = "ShopServicePort")
    public ShopService getShopServicePort() {
        return super.getPort(new QName("http://mikovoz.com/", "ShopServicePort"), ShopService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ShopService
     */
    @WebEndpoint(name = "ShopServicePort")
    public ShopService getShopServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mikovoz.com/", "ShopServicePort"), ShopService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SHOPSERVICESERVICE_EXCEPTION!= null) {
            throw SHOPSERVICESERVICE_EXCEPTION;
        }
        return SHOPSERVICESERVICE_WSDL_LOCATION;
    }

}
